config/routes.rb
Rails.application.routes.draw do
  resources :examples
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/example.rb
class Example < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/examples_controller.rb
class ExamplesController < ApplicationController
  before_action :set_example, only: %i[ show edit update destroy ]

  # GET /examples or /examples.json
  def index
    @examples = Example.all
  end

  # GET /examples/1 or /examples/1.json
  def show
  end

  # GET /examples/new
  def new
    @example = Example.new
  end

  # GET /examples/1/edit
  def edit
  end

  # POST /examples or /examples.json
  def create
    @example = Example.new(example_params)

    respond_to do |format|
      if @example.save
        format.html { redirect_to @example, notice: "Example was successfully created." }
        format.json { render :show, status: :created, location: @example }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examples/1 or /examples/1.json
  def update
    respond_to do |format|
      if @example.update(example_params)
        format.html { redirect_to @example, notice: "Example was successfully updated." }
        format.json { render :show, status: :ok, location: @example }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @example.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examples/1 or /examples/1.json
  def destroy
    @example.destroy!

    respond_to do |format|
      format.html { redirect_to examples_path, status: :see_other, notice: "Example was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_example
      @example = Example.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def example_params
      params.require(:example).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/views/examples/_example.html.erb
<div id="<%= dom_id example %>">
  <p>
    <strong>Title:</strong>
    <%= example.title %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= example.content %>
  </p>

</div>

app/views/examples/_form.html.erb
<%= form_with(model: example) do |form| %>
  <% if example.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(example.errors.count, "error") %> prohibited this example from being saved:</h2>

      <ul>
        <% example.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/examples/edit.html.erb
<% content_for :title, "Editing example" %>

<h1>Editing example</h1>

<%= render "form", example: @example %>

<br>

<div>
  <%= link_to "Show this example", @example %> |
  <%= link_to "Back to examples", examples_path %>
</div>

app/views/examples/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Examples" %>

<h1>Examples</h1>

<div id="examples">
  <% @examples.each do |example| %>
    <%= render example %>
    <p>
      <%= link_to "Show this example", example %>
    </p>
  <% end %>
</div>

<%= link_to "New example", new_example_path %>

app/views/examples/new.html.erb
<% content_for :title, "New example" %>

<h1>New example</h1>

<%= render "form", example: @example %>

<br>

<div>
  <%= link_to "Back to examples", examples_path %>
</div>

app/views/examples/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @example %>

<div>
  <%= link_to "Edit this example", edit_example_path(@example) %> |
  <%= link_to "Back to examples", examples_path %>

  <%= button_to "Destroy this example", @example, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>